version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "06:00"
    open-pull-requests-limit: 5
    versioning-strategy: auto
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "06:00"
    open-pull-requests-limit: 5
